services:
  lsdb-server:
    image: troyraen/lsdb-server:latest
    container_name: lsdb-server
    ports:
      - "8000:8000"
  firefly:
    image: ipac/firefly:latest
    container_name: firefly
    ports:
      - "80:8080"
    volumes:
      # Map the endpoint http://<BASE-URL>/local to the firefly-html/ directory.
      - ./firefly-html:/local/www
    mem_limit: 4g
    environment:
      # Point Gator at lsdb-server.
      - PROPS=irsa.gator.dd.hostname=http://lsdb-server:8000 irsa.gator.hostname=http://lsdb-server:8000
